import cart from "../assets/images/cart.png";
import logo from "../assets/images/logo.png";
import menu from "../assets/images/menu.png";
import search from "../assets/images/search.png";
import heroVans from "../assets/images/vans-black-december-sale.jpg";
import shopNow from "../assets/images/shopnow.jpg";
import knuSkools from "../assets/images/knuSkools.jpg";
import menWomenSquare from '../assets/images/menWomenSquare.jpg';
import menWomenSquareTwo from '../assets/images/menWomenSquareTwo.jpg';
import blog1 from "../assets/images/blog1.jpg";
import blog2 from "../assets/images/blog2.jpg";
import blog3 from "../assets/images/blob3.webp";
import blog4 from "../assets/images/blog4.jpg";
import loading from '../assets/images/loader-spinner-vans.gif';
import categoriesMen from '../assets/images/hp_categories_men.jpg';
import categoriesWomen from '../assets/images/hp_categories_women.jpg';
import categoriesKids from '../assets/images/hp_categories_kids.jpg';
import customer from '../assets/images/account.png';
import warning from '../assets/images/warning.png';
import exit from '../assets/images/exit.png';
import buyMe from '../assets/images/buyMe.jpg';
import payPal from '../assets/images/payPal.png';
import vansMain from '../assets/images/vans-main.png';
import listStar from '../assets/images/list-star.webp';

export default {listStar, vansMain, payPal, buyMe, warning, cart, exit, logo, menu, search, heroVans, shopNow, knuSkools, menWomenSquare, menWomenSquareTwo, blog1, blog2, blog3, blog4, loading, categoriesMen, categoriesWomen, categoriesKids, customer };
