import {gql} from "@apollo/client";

export const GET_CUSTOMER_DETAILS = gql`
    query getCustomerDetails {
        customer{
            addresses{
                city
                company
                default_billing
                default_shipping
                extension_attributes{
                    attribute_code
                    value
                }
                fax
                firstname
                id
                lastname
                middlename
                postcode
                prefix
                region{
                    region
                    region_code
                }
                street
                suffix
                telephone
                vat_id
            }
            created_at
            date_of_birth
            default_billing
            default_shipping
            email
            firstname
            gender
            is_subscribed
            lastname
            middlename
            prefix
            suffix
            taxvat
            wishlist{
                id
                items_count
                sharing_code
                updated_at
                items{
                    added_at
                    description
                    id
                    qty
                    product{
                        activity
                        attribute_set_id
                        canonical_url
                        categories{
                            id
                            url_key
                            name
                            path
                            url_suffix
                        }
                        category_gear
                        climate
                        collar
                        color
                        color_family
                        country_of_manufacture
                        created_at
                        crosssell_products{
                            name
                            sku
                        }
                        description{
                            html
                        }
                        description_1
                        description_2
                        description_3
                        eco_collection
                        erin_recommends
                        features_bags
                        format
                        gamechanger
                        gender
                        gender_filter
                        gift_message_available
                        hover
                        id
                        image{
                            label
                            url
                        }
                        manufacturer
                        meta_description
                        meta_keyword
                        meta_title
                        name
                        new
                        new_from_date
                        new_to_date
                        only_x_left_in_stock
                        options_container
                        pattern
                        performance_fabric
                        price_range{
                            maximum_price{
                                discount{
                                    amount_off
                                    percent_off
                                }
                                final_price{
                                    currency
                                    value
                                }
                                fixed_product_taxes{
                                    amount{
                                        currency
                                        value
                                    }
                                    label
                                }
                                regular_price{
                                    currency
                                    value
                                }
                            }
                            minimum_price{
                                discount{
                                    amount_off
                                    percent_off
                                }
                                final_price{
                                    currency
                                    value
                                }
                                fixed_product_taxes{
                                    amount{
                                        currency
                                        value
                                    }
                                    label
                                }
                                regular_price{
                                    currency
                                    value
                                }
                            }
                        }
                        price_tiers{
                            discount{
                                amount_off
                                percent_off
                            }
                            final_price{
                                currency
                                value
                            }
                            quantity
                        }
                        product_links{
                            link_type
                            linked_product_sku
                            linked_product_type
                            position
                            sku
                        }
                        product_skus
                        sale
                        short_description{
                            html
                        }
                        size
                        sku
                        sleeve
                        small_image{
                            label
                            url
                        }
                        special_from_date
                        special_price
                        stock_status
                        strap_bags
                        style_bags
                        style_bottom
                        style_general
                        swatch_image
                        thumbnail{
                            label
                            url
                        }
                        updated_at
                        upsell_products{
                            name
                            sku
                        }
                        url_key
                        url_rewrites{
                            parameters{
                                name
                                value
                            }
                            url
                        }
                        url_suffix
                    }
                }
            }
        }
    }
`;

export const REVOKE_CUSTOMER_TOKEN = gql`
    mutation{
        revokeCustomerToken{
            result
        }
    }
`;

export const SIGN_IN = gql`
    mutation ($email: String!, $password: String!) {
        generateCustomerToken(email: $email, password: $password){
            token
        }
    }
`;

export const GET_CUSTOMER_ORDERS = gql`
    query{
        customerOrders{
            items{
                id
                order_number
                status
                grand_total
                created_at
                payment_method
                shipping_method
                shipping_address{
                    city
                    company
                    fax
                    firstname
                    lastname
                    middlename
                    postcode
                    prefix
                    region
                    street
                    suffix
                    telephone
                    vat_id
                }
                billing_address {
                    city
                    company
                    fax
                    firstname
                    lastname
                    middlename
                    postcode
                    prefix
                    region
                    street
                    suffix
                    telephone
                    vat_id
                }
                products{
                    price
                    product_name
                    quantity_ordered
                    sku
                    product{
                        activity
                        attribute_set_id
                        canonical_url
                        categories{
                            id
                            url_key
                            name
                            path
                            url_suffix
                        }
                        category_gear
                        climate
                        collar
                        color
                        color_family
                        created_at
                        country_of_manufacture
                        crosssell_products{
                            name
                            sku
                        }
                        description{
                            html
                        }
                        description_1
                        description_2
                        description_3
                        eco_collection
                        erin_recommends
                        features_bags
                        format
                        gamechanger
                        gender
                        gender_filter
                        gift_message_available
                        hover
                        id
                        image{
                        label
                        url
                        }
                        manufacturer
                        meta_description
                        meta_keyword
                        meta_title
                        name
                        new
                        new_from_date
                        new_to_date
                        only_x_left_in_stock
                        options_container
                        pattern
                        performance_fabric
                        price_range{
                            maximum_price{
                                discount{
                                    amount_off
                                    percent_off
                                }
                                final_price{
                                    currency
                                    value
                                }
                                fixed_product_taxes{
                                    amount{
                                        currency
                                        value
                                    }
                                    label
                                }
                                regular_price{
                                    currency
                                    value
                                }
                            }
                            minimum_price{
                                discount{
                                    amount_off
                                    percent_off
                                }
                                final_price{
                                    currency
                                    value
                                }
                                fixed_product_taxes{
                                    amount{
                                        currency
                                        value
                                    }
                                    label
                                }
                                regular_price{
                                    currency
                                    value
                                }
                            }
                        }
                        price_tiers{
                            discount{
                                amount_off
                                percent_off
                            }
                            final_price{
                                currency
                                value
                            }
                            quantity
                        }
                        product_links{
                            link_type
                            linked_product_sku
                            linked_product_type
                            position
                            sku
                        }
                        product_skus
                        sale
                        short_description{
                            html
                        }
                        size
                        sku
                        sleeve
                        small_image{
                            label
                            url
                        }
                        special_from_date
                        special_price
                        stock_status
                        strap_bags
                        style_bags
                        style_bottom
                        style_general
                        swatch_image
                        thumbnail{
                            label
                            url
                        }
                        updated_at
                        url_key
                        url_suffix
                    }
                }
            }
        }
    }
`;