import { gql } from '@apollo/client';

export const CheckoutPageFragment = gql`
    fragment CheckoutPageFragment on Cart {
        id
        items {
            id
            product {
                id
                stock_status
            }
        }
        billing_address{
        city
        company
        country{
          code
          label
        }
        firstname
        lastname
        postcode
        region{
          code
          label
        }
        street
        telephone
      }
      shipping_addresses{
        available_shipping_methods{
            amount{
                currency
                value
            }
            available
            carrier_code
            carrier_title
            error_message
            method_code
            method_title
            price_excl_tax{
                currency
                value
            }
            price_incl_tax{
                currency
                value
            }
        }
        city
        company
        country{
          code
          label
        }
        customer_notes
        firstname
        lastname
        postcode
        region{
          code
          label
        }
        street
        telephone
        selected_shipping_method{
            amount{
                currency
                value
            }
            carrier_code
            carrier_title
            method_code
            method_title
        }
      }
      prices{
        applied_taxes{
          amount {
            currency
            value
          }
          label
        }
        discounts{
          amount {
            currency
            value
          }
          label
        }
        grand_total{
          currency
          value
        }
        subtotal_excluding_tax{
          currency
          value
        }
        subtotal_including_tax{
          currency
          value
        }
        subtotal_with_discount_excluding_tax{
          currency
          value
        }
      }
        total_quantity
        available_payment_methods {
            title
            code
        }
    }
`;
