import {gql} from "@apollo/client";

export const GET_CATEGORY = gql`
query getCategory ($ids: String!){
  categoryList(filters: {ids: {in: [$ids]}}){
    name
    path
    path_in_store
    pl_size_chart
    position
    product_count
    updated_at
    url_key
    url_path
    url_suffix
    children_count
  }
}
`;

export const GET_PRODUCTS = gql`
query getProducts ($filter: ProductAttributeFilterInput!){
  products(filter: $filter, pageSize: 40){
      items{
        activity
        attribute_set_id
        canonical_url
        categories{
          id
          url_key
          name
          path
          url_suffix
        }
        category_gear
        climate
        collar
        color
        color_family
        country_of_manufacture
        created_at
        crosssell_products{
          name
          sku
        }
        description{
          html
        }
        description_1
        description_2
        description_3
        eco_collection
        erin_recommends
        features_bags
        format
        gamechanger
        gender
        gender_filter
        gift_message_available
        hover
        id
        image{
          label
          url
        }
        manufacturer
        meta_description
        meta_keyword
        meta_title
        name
        new
        new_from_date
        new_to_date
        only_x_left_in_stock
        options_container
        pattern
        performance_fabric
        price_range{
          maximum_price{
            discount{
              amount_off
              percent_off
            }
            final_price{
              currency
              value
            }
            fixed_product_taxes{
              amount{
                currency
                value
              }
              label
            }
            regular_price{
              currency
              value
            }
          }
          minimum_price{
            discount{
              amount_off
              percent_off
            }
            final_price{
              currency
              value
            }
            fixed_product_taxes{
              amount{
                currency
                value
              }
              label
            }
            regular_price{
              currency
              value
            }
          }
        }
        price_tiers{
          discount{
            amount_off
            percent_off
          }
          final_price{
            currency
            value
          }
          quantity
        }
        product_links{
          link_type
          linked_product_sku
          linked_product_type
          position
          sku
        }
        product_skus
        sale
        short_description{
          html
        }
        size
        sku
        sleeve
        small_image{
          label
          url
        }
        special_from_date
        special_price
        stock_status
        strap_bags
        style_bags
        style_bottom
        style_general
        swatch_image
        thumbnail{
          label
          url
        }
        updated_at
        upsell_products{
          name
          sku
        }
        url_key
        url_rewrites{
          parameters{
            name
            value
          }
          url
        }
        url_suffix
      }
    }
  }
`;

export const GET_PRODUCT_FILTERS_BY_CATEGORY = gql`
    query getProductFiltersByCategory ($categoryIdFilter: FilterEqualTypeInput! ) {
        products(filter: { category_id: $categoryIdFilter }) {
            aggregations {
                label
                count
                attribute_code
                options {
                    label
                    value
                  count
                }
            }
            sort_fields{
                default
                options{
                    label
                    value
                }
            }
        }
    }
`;