import { gql } from '@apollo/client';

export const GET_PRODUCT_DETAIL_QUERY = gql`
    query getProductDetailForProductPage($urlKey: String!) {
        products(filter: { url_key: { eq: $urlKey } }) {
            items {
                activity
                attribute_set_id
                color_val
                gender_filter_val
                ... on ConfigurableProduct {
                    configurable_options {
                        attribute_id
                        attribute_code
                        label
                        values {
                          value_index
                          label
                        }
                    }
                    variants {
                    product {
                      id
                      name
                      sku
                      stock_status
                      color_val
                      gender_filter_val
                      media_gallery{
                    label
                    url
                }
                      price {
                        regularPrice {
                          amount {
                            value
                            currency
                          }
                        }
                      }
                    }
                    attributes {
                      code
                      value_index
                    }
                }
                }
                canonical_url
                categories{
                  id
                  url_key
                  name
                  path
                  url_suffix
                  breadcrumbs{
                    category_id
                  }
                }
                category_gear
                climate
                collar
                color
                color_family
                country_of_manufacture
                created_at
                crosssell_products{
                  name
                  sku
                }
                description{
                  html
                }
                description_1
                description_2
                description_3
                eco_collection
                erin_recommends
                features_bags
                format
                gamechanger
                gender
                gender_filter
                gift_message_available
                hover
                id
                image{
                  label
                  url
                }
                manufacturer
                media_gallery{
                    label
                    url
                }
                meta_description
                meta_keyword
                meta_title
                name
                new
                new_from_date
                new_to_date
                only_x_left_in_stock
                options_container
                pattern
                performance_fabric
                price_range{
                  maximum_price{
                    discount{
                      amount_off
                      percent_off
                    }
                    final_price{
                      currency
                      value
                    }
                    fixed_product_taxes{
                      amount{
                        currency
                        value
                      }
                      label
                    }
                    regular_price{
                      currency
                      value
                    }
                  }
                  minimum_price{
                    discount{
                      amount_off
                      percent_off
                    }
                    final_price{
                      currency
                      value
                    }
                    fixed_product_taxes{
                      amount{
                        currency
                        value
                      }
                      label
                    }
                    regular_price{
                      currency
                      value
                    }
                  }
                }
                price_tiers{
                  discount{
                    amount_off
                    percent_off
                  }
                  final_price{
                    currency
                    value
                  }
                  quantity
                }
                product_links{
                  link_type
                  linked_product_sku
                  linked_product_type
                  position
                  sku
                }
                product_skus
                sale
                short_description{
                  html
                }
                size
                sku
                sleeve
                small_image{
                  label
                  url
                }
                special_from_date
                special_price
                stock_status
                strap_bags
                style_bags
                style_bottom
                style_general
                swatch_image
                thumbnail{
                  label
                  url
                }
                updated_at
                upsell_products{
                  name
                  sku
                }
                url_key
                url_rewrites{
                  parameters{
                    name
                    value
                  }
                  url
                }
                url_suffix
            }
        }
    }
`;

export const GET_POPULAR_PRODUCTS = gql`
query getPopularProducts{
  getPopularProducts {
    title
    popular_products {
        title
        image
        url
        price
    }
  }
}
`;
